name: Publishable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dry_run:
    name: Dry run publish on ${{ matrix.os }}
    if: github.repository == 'fluttercandies/flutter_ali_auth'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          dryRunOnly: true
